kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: k8s-example-ui
  namespace: k8s-example
spec:
  replicas: 1
  template:
    metadata:
      name: ui
      labels:
        app: k8s-example
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      containers:
      - name: ui
        image: gcr.io/crested-pursuit-257317/k8s-example-ui
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-example
  name: k8s-example-ui
  namespace: k8s-example
spec:
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: k8s-example
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-example-ui
  namespace: k8s-example
spec:
  hosts:
    - "example.kubernetesclustertest.com"
  gateways:
    - public-gateway.istio-system.svc.cluster.local
  http:
    - route:
        - destination:
            host: k8s-example-ui
            port:
              number: 80
      timeout: 30s
